#' @rdname sen2r

# Internal accessory function used to list s2names()
list_sen2r_paths <- function(param_list = NULL,
                             gui = NA,
                             preprocess = TRUE,
                             s2_levels = c("l1c","l2a"),
                             sel_sensor = c("s2a","s2b"),
                             online = TRUE,
                             apihub = NA,
                             downloader = "wget",
                             overwrite_safe = FALSE,
                             rm_safe = "no",
                             step_atmcorr = "auto",
                             timewindow = NA,
                             timeperiod = "full",
                             extent = NA, # below re-defined as sample extent if online mode
                             extent_name = "",
                             s2tiles_selected = NA, # below re-defined for online mode
                             s2orbits_selected = NA, # temporary select all orbits (TODO implement)
                             list_prods = c("BOA"),
                             list_indices = NA,
                             index_source = "BOA",
                             mask_type = NA,
                             max_mask = 100,
                             mask_smooth = 0,
                             mask_buffer = 0,
                             clip_on_extent = TRUE,
                             extent_as_mask = FALSE,
                             reference_path = NA,
                             res = NA,
                             res_s2 = "10m",
                             unit = "Meter",
                             proj = NA,
                             resampling = "near",
                             resampling_scl = "near",
                             outformat = "GTiff",
                             index_datatype = "Int16",
                             compression = "DEFLATE",
                             overwrite = FALSE,
                             path_l1c = NA,
                             path_l2a = NA,
                             path_tiles = NA,
                             path_merged = NA,
                             path_out = NA,
                             path_indices = NA,
                             path_subdirs = TRUE,
                             thumbnails = TRUE,
                             parallel = TRUE,
                             use_python = TRUE,
                             tmpdir = NA,
                             rmtmp = TRUE, 
                             log = NA) {
  
  # filter names of passed arguments
  sen2r_args <- formalArgs(sen2r:::.sen2r)
  sen2r_args <- sen2r_args[!sen2r_args %in% c(".log_message",".log_output",".only_list_names")]
  pm_arg_passed <- logical(0)
  for (i in seq_along(sen2r_args)) {
    pm_arg_passed[i] <- !do.call(missing, list(sen2r_args[i]))
  }
  
  # launch the function
  sen2r:::.sen2r(
    param_list = param_list,
    pm_arg_passed = pm_arg_passed,
    gui = gui,
    preprocess = preprocess,
    s2_levels = s2_levels,
    sel_sensor = sel_sensor,
    online = online,
    apihub = apihub,
    downloader = downloader,
    overwrite_safe = overwrite_safe,
    rm_safe = rm_safe,
    step_atmcorr = step_atmcorr,
    timewindow = timewindow,
    timeperiod = timeperiod,
    extent = extent,
    extent_name = extent_name,
    s2tiles_selected = s2tiles_selected,
    s2orbits_selected = s2orbits_selected,
    list_prods = list_prods,
    list_indices = list_indices,
    index_source = index_source,
    mask_type = mask_type,
    max_mask = max_mask,
    mask_smooth = mask_smooth,
    mask_buffer = mask_buffer,
    clip_on_extent = clip_on_extent,
    extent_as_mask = extent_as_mask,
    reference_path = reference_path,
    res = res,
    res_s2 = res_s2,
    unit = unit,
    proj = proj,
    resampling = resampling,
    resampling_scl = resampling_scl,
    outformat = outformat,
    index_datatype = index_datatype,
    compression = compression,
    overwrite = overwrite,
    path_l1c = path_l1c,
    path_l2a = path_l2a,
    path_tiles = path_tiles,
    path_merged = path_merged,
    path_out = path_out,
    path_indices = path_indices,
    path_subdirs = path_subdirs,
    thumbnails = thumbnails,
    parallel = parallel,
    use_python = use_python,
    tmpdir = tmpdir,
    rmtmp = rmtmp,
    .log_message = NA, .log_output = NA,
    .only_list_names = TRUE
  )
  
}
